import type { PlanEntitlements } from "./schema.js";

// Seed data from docs/design/domain/overview.md (event types) and
// docs/design/features/plans-and-billing.md (plans).

export const EVENT_TYPES = [
  { key: "wedding", nameSw: "Harusi", nameEn: "Wedding" },
  { key: "send_off", nameSw: "Send-off", nameEn: "Send-off" },
  { key: "kitchen_party", nameSw: "Kitchen Party", nameEn: "Kitchen party" },
  { key: "birthday", nameSw: "Siku ya Kuzaliwa", nameEn: "Birthday" },
  { key: "graduation", nameSw: "Mahafali", nameEn: "Graduation" },
  { key: "other", nameSw: "Nyingine", nameEn: "Other" },
] as const;

const noMedia: PlanEntitlements["media"] = {
  cardPhotos: 0,
  cardVideoSeconds: 0,
  animatedCard: false,
  storyPhotos: 0,
  storyVideos: 0,
  storyVideoSeconds: 0,
  gallery: false,
  galleryVideoSeconds: 0,
  galleryUploadDaysAfter: 0,
  galleryPageMonths: 0,
  galleryUploadsPerGuest: 0,
  slideshow: false,
};

export const PLANS: { key: string; name: string; pricePerGuest: number; entitlements: PlanEntitlements }[] = [
  {
    key: "msingi",
    name: "Msingi",
    pricePerGuest: 1000,
    entitlements: {
      doorStaffAccounts: 2,
      autoUpgrade: false,
      maxContributionReminders: 0,
      channelPerMessage: false,
      smsWordingEdit: false,
      maxSmsSegments: 1,
      whatsappTemplateStyles: false,
      customTiming: false,
      maxManualSends: 0,
      marketingMessages: false,
      media: noMedia,
    },
  },
  {
    key: "kawaida",
    name: "Kawaida",
    pricePerGuest: 1500,
    entitlements: {
      doorStaffAccounts: 5,
      autoUpgrade: true,
      maxContributionReminders: 3,
      channelPerMessage: true,
      smsWordingEdit: true,
      maxSmsSegments: 1,
      whatsappTemplateStyles: true,
      customTiming: true,
      maxManualSends: 2,
      marketingMessages: false,
      media: {
        cardPhotos: 5,
        cardVideoSeconds: 30,
        animatedCard: false,
        storyPhotos: 20,
        storyVideos: 1,
        storyVideoSeconds: 60,
        gallery: true,
        galleryVideoSeconds: 30,
        galleryUploadDaysAfter: 3,
        galleryPageMonths: 3,
        galleryUploadsPerGuest: 20,
        slideshow: false,
      },
    },
  },
  {
    key: "premium",
    name: "Premium",
    pricePerGuest: 2000,
    entitlements: {
      doorStaffAccounts: null,
      autoUpgrade: true,
      maxContributionReminders: 6,
      channelPerMessage: true,
      smsWordingEdit: true,
      maxSmsSegments: 2,
      whatsappTemplateStyles: true,
      customTiming: true,
      maxManualSends: 5,
      marketingMessages: true,
      media: {
        cardPhotos: 10,
        cardVideoSeconds: 60,
        animatedCard: true,
        storyPhotos: 50,
        storyVideos: 5,
        storyVideoSeconds: 120,
        gallery: true,
        galleryVideoSeconds: 60,
        galleryUploadDaysAfter: 7,
        galleryPageMonths: 12,
        galleryUploadsPerGuest: 50,
        slideshow: true,
      },
    },
  },
];
