name: dcard_door
description: "D-Card Door app for check-in at the event entrance."
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dcard_api: any
  dcard_core: any
  dcard_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
